
# game-related constants

# allowed stats and their groupings

OFFENSIVE_STAT_NAMES = [ "Att", "Off", "Str", "AP", "Agi" ]
DEFENSIVE_STAT_NAMES = ["HP", "Def", "Res", "Arm"]
GENERAL_STAT_NAMES = ["Adv", "Mar", "Dis"]

GENERAL_AND_DEFENSIVE_STAT_NAMES = GENERAL_STAT_NAMES + DEFENSIVE_STAT_NAMES
ALL_STAT_NAMES = GENERAL_STAT_NAMES + DEFENSIVE_STAT_NAMES + OFFENSIVE_STAT_NAMES

# allowed special rules

GENERAL_SPECIAL_RULES = ["FEAR", "FEARLESS", "UNBREAKABLE"]
DEFENSIVE_SPECIAL_RULES = ["FORTITUDE", "AEGIS", "DISTRACTING", "PARRY", "HARDTARGET"]
OFFENSIVE_SPECIAL_RULES = ["HATRED", "POISON", "LETHALSTRIKE" , "LIGHTNINGREFLEXES", "FIER"]

GENERAL_AND_DEFENSIVE_SPECIAL_RULES = GENERAL_SPECIAL_RULES + DEFENSIVE_SPECIAL_RULES
ALL_SPECIAL_RULES = GENERAL_SPECIAL_RULES + DEFENSIVE_SPECIAL_RULES + OFFENSIVE_SPECIAL_RULES

# tables for hitting and wounding

TO_HIT_TABLE = { -10: 1, -9: 1, -8: 1, -7: 2, -6: 2, -5: 2, -4: 2, -3: 3, -2: 3, -1: 3,
                       0: 3, 1: 4, 2: 4, 3: 4, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5, 9: 5, 10: 5  }